export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  isVeg?: boolean;
  weight?: string;
  perfectMatch?: string;
  image?: string;
}

export const categories = [
  { id: "sweets", name: "Sweets", icon: "🍬" },
  { id: "namkeens", name: "Namkeens", icon: "🥜" },
  { id: "pizza", name: "Pizza", icon: "🍕" },
  { id: "burgers", name: "Burgers", icon: "🍔" },
  { id: "hotdogs", name: "Hot Dogs", icon: "🌭" },
  { id: "sandwiches", name: "Sandwiches", icon: "🥪" },
  { id: "snacks", name: "Chat & Snacks", icon: "🍢" },
  { id: "puffs", name: "Puffs", icon: "🥐" },
  { id: "biscuits", name: "Biscuits", icon: "🍪" },
  { id: "pastries", name: "Pastries", icon: "🍰" },
  { id: "cakes", name: "Cakes", icon: "🎂" },
] as const;

export const menuItems: MenuItem[] = [
  // Sweets - Regular (250g/500g/1kg options, using 250g price)
  {
    id: "sw1",
    name: "Mixed Sweets",
    description: "Assorted traditional Indian sweets (500g: ₹390, 1kg: ₹780)",
    price: 195,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw2",
    name: "Motichur Laddu",
    description: "Golden boondi laddus (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw3",
    name: "Ajmeri Kalakand",
    description: "Rich milk cake from Ajmer (500g: ₹390, 1kg: ₹780)",
    price: 195,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw4",
    name: "White Kalakand",
    description: "Creamy white milk fudge (500g: ₹390, 1kg: ₹780)",
    price: 195,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw5",
    name: "Badusha",
    description: "Flaky layered sweet (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw6",
    name: "Kova Puri",
    description: "Stuffed kova sweet (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw7",
    name: "Madatha Khaja",
    description: "Layered crispy sweet (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw8",
    name: "Dry Fruit Halwa",
    description: "Rich halwa with nuts (500g: ₹380, 1kg: ₹760)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw9",
    name: "Bombay Halwa",
    description: "Gelatinous Mumbai-style halwa (500g: ₹380, 1kg: ₹760)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw10",
    name: "Bandar Laddu",
    description: "Famous Machilipatnam laddu (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw11",
    name: "Beshan Laddu",
    description: "Gram flour laddu (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw12",
    name: "Boondi Laddu",
    description: "Classic boondi laddu (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw13",
    name: "Nuvvula Laddu (Til Laddu)",
    description: "Sesame seeds laddu (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw14",
    name: "Ice Cream Burfi",
    description: "Cool creamy burfi (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw15",
    name: "Vanilla Burfi",
    description: "Vanilla flavored milk burfi (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw16",
    name: "Standard Burfi",
    description: "Classic milk burfi (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw17",
    name: "Soan Patti",
    description: "Crispy flaky sweet (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw18",
    name: "Soan Papdi",
    description: "Layered crispy cubes (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw19",
    name: "Milk Mysore Pak",
    description: "Soft milk mysore pak (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw20",
    name: "Jali Mysore Pak",
    description: "Crispy netted mysore pak (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw21",
    name: "Bellam Sunnundalu",
    description: "Jaggery urad dal laddu (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw22",
    name: "Sugar Sunnundalu",
    description: "Sweet urad dal laddu (500g: ₹370, 1kg: ₹740)",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  // Sweets - Pieces
  {
    id: "sw23",
    name: "Dry Fruit Bellam Putharekulu",
    description: "Dry fruit jaggery paper sweet - 3 pieces",
    price: 150,
    category: "sweets",
    isVeg: true,
    weight: "3 pieces",
  },
  {
    id: "sw24",
    name: "Bellam Putharekulu",
    description: "Jaggery paper sweet - 3 pieces",
    price: 120,
    category: "sweets",
    isVeg: true,
    weight: "3 pieces",
  },
  {
    id: "sw25",
    name: "Sugar Putharekulu",
    description: "Sugar paper sweet - 3 pieces",
    price: 100,
    category: "sweets",
    isVeg: true,
    weight: "3 pieces",
  },
  {
    id: "sw26",
    name: "Rasmalai",
    description: "Soft cottage cheese patties in saffron milk - 3 pieces",
    price: 120,
    category: "sweets",
    isVeg: true,
    weight: "3 pieces",
  },
  {
    id: "sw27",
    name: "Rasagulla",
    description: "Spongy syrup soaked sweets - 3 pieces",
    price: 120,
    category: "sweets",
    isVeg: true,
    weight: "3 pieces",
  },
  {
    id: "sw28",
    name: "Gulab Jamun",
    description: "Deep fried milk solids in sugar syrup - 3 pieces",
    price: 120,
    category: "sweets",
    isVeg: true,
    weight: "3 pieces",
  },
  {
    id: "sw29",
    name: "Kala Jamun",
    description: "Dark fried sweets in sugar syrup - 3 pieces",
    price: 120,
    category: "sweets",
    isVeg: true,
    weight: "3 pieces",
  },
  // Premium Sweets - Kaju/Dry Fruit (250g/500g/1kg)
  {
    id: "sw30",
    name: "Kaju Barfi",
    description: "Diamond shaped cashew sweet (500g: ₹700, 1kg: ₹1400)",
    price: 350,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw31",
    name: "Kaju Kathli",
    description: "Thin cashew slices (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw32",
    name: "All Dry Fruit Mixed Sweets",
    description: "Assorted premium dry fruit sweets (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw33",
    name: "Anjeer Roll",
    description: "Fig and nut roll (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw34",
    name: "Kaju Pista Roll",
    description: "Cashew and pistachio roll (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw35",
    name: "Kaju Chikki",
    description: "Cashew brittle (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw36",
    name: "Dry Fruit Laddu",
    description: "Nutty dry fruit laddu (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw37",
    name: "Dry Fruit Chikki",
    description: "Mixed nut brittle (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw38",
    name: "Kaju Bites",
    description: "Bite-sized cashew sweets (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "sw39",
    name: "Kaju Sandwich",
    description: "Layered cashew sweet (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
  },

  // Namkeens (250g/500g/1kg, using 250g price)
  {
    id: "nk1",
    name: "Amogha Special Mixture",
    description: "Signature savory mix (500g: ₹240, 1kg: ₹480)",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk2",
    name: "Special Khara Boondi",
    description: "Spicy fried boondi (500g: ₹240, 1kg: ₹480)",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk3",
    name: "Kaju Mixture",
    description: "Premium cashew mix (500g: ₹300, 1kg: ₹600)",
    price: 150,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk4",
    name: "Batana Mixture",
    description: "Chickpea flour savory (500g: ₹300, 1kg: ₹600)",
    price: 150,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk5",
    name: "Dalmoti",
    description: "Lentil based savory (500g: ₹300, 1kg: ₹600)",
    price: 150,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk6",
    name: "Masala Palli",
    description: "Spiced peanut snack (500g: ₹240, 1kg: ₹480)",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk7",
    name: "Khara Pusa",
    description: "Spicy puffed rice (500g: ₹240, 1kg: ₹480)",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk8",
    name: "Masala Mixture",
    description: "Spiced savory mix (500g: ₹240, 1kg: ₹480)",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk9",
    name: "Corn Mixture",
    description: "Corn based savory (500g: ₹240, 1kg: ₹480)",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk10",
    name: "Ghatiya",
    description: "Gujarati style sev (500g: ₹240, 1kg: ₹480)",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk11",
    name: "Papdi",
    description: "Crispy fried discs (500g: ₹240, 1kg: ₹480)",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk12",
    name: "Namak Pare",
    description: "Salty fried strips (500g: ₹240, 1kg: ₹480)",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk13",
    name: "Ghee Roasted Salted Kaju",
    description: "Ghee roasted salted cashews (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk14",
    name: "Ghee Roasted Masala Kaju",
    description: "Spiced ghee roasted cashews (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk15",
    name: "Ghee Roasted Pepper Kaju",
    description: "Pepper ghee roasted cashews (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },
  {
    id: "nk16",
    name: "Ghee Roasted Almonds",
    description: "Ghee roasted badam (500g: ₹780, 1kg: ₹1560)",
    price: 390,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
  },

  // Chat
  {
    id: "ch1",
    name: "Pani Puri",
    description: "20 crispy shells with spicy flavored water",
    price: 100,
    category: "snacks",
    isVeg: true,
    weight: "20 pieces",
  },
  {
    id: "ch2",
    name: "Vada Pav",
    description: "Mumbai's favorite potato fritter in a bun",
    price: 90,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch3",
    name: "Samosa Ragada",
    description: "Samosa with spiced white pea curry",
    price: 90,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch4",
    name: "Butter Pav Bhaji",
    description: "Buttery mashed vegetable curry with bread",
    price: 110,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch5",
    name: "Pav Bhaji",
    description: "Classic mashed vegetable curry with bread",
    price: 100,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch6",
    name: "Paneer Pav Bhaji",
    description: "Pav bhaji with paneer topping",
    price: 120,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch7",
    name: "Cheese Pav Bhaji",
    description: "Pav bhaji with cheese topping",
    price: 120,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch8",
    name: "Masala Pav Bhaji",
    description: "Spiced pav bhaji with extra masala",
    price: 110,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch9",
    name: "Samosa Cutlet",
    description: "Samosa and cutlet combination chaat",
    price: 90,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch10",
    name: "Cutlet Chaat",
    description: "Vegetable cutlet with chutneys",
    price: 90,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch11",
    name: "Dahi Samosa",
    description: "Samosa topped with yogurt and chutneys",
    price: 90,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch12",
    name: "Dahi Papdi",
    description: "Crispy papdi with yogurt and chutneys",
    price: 100,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch13",
    name: "Bhel Puri",
    description: "Crispy puffed rice with chutneys and sev",
    price: 90,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch14",
    name: "Kachori Chaat",
    description: "Stuffed kachori with chutneys",
    price: 90,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "ch15",
    name: "Papdi Chaat",
    description: "Flat puris with potato, yogurt and chutneys",
    price: 90,
    category: "snacks",
    isVeg: true,
  },

  // Cakes
  {
    id: "ck1",
    name: "Pineapple Cake (1/2 Kg)",
    description: "Fresh cream cake with pineapple topping",
    price: 319,
    category: "cakes",
    isVeg: true,
    weight: "500 gms",
  },
  {
    id: "ck2",
    name: "Butterscotch Cake (1/2 Kg)",
    description: "Caramel-flavored cake with praline",
    price: 349,
    category: "cakes",
    isVeg: true,
    weight: "500 gms",
  },
  {
    id: "ck3",
    name: "Black Forest Cake (1/2 Kg)",
    description: "Chocolate cake with whipped cream and cherries",
    price: 349,
    category: "cakes",
    isVeg: true,
    weight: "500 gms",
  },
  {
    id: "ck4",
    name: "Chocolate Cake (1/2 Kg)",
    description: "Rich chocolate cream cake",
    price: 449,
    category: "cakes",
    isVeg: true,
    weight: "500 gms",
  },
  {
    id: "ck5",
    name: "Rasmalai Cake (1/2 Kg)",
    description: "Fusion cake with rasmalai flavor",
    price: 449,
    category: "cakes",
    isVeg: true,
    weight: "500 gms",
  },
  {
    id: "ck6",
    name: "Almond Cake (1/2 Kg)",
    description: "Cake with almond crunch and flavor",
    price: 449,
    category: "cakes",
    isVeg: true,
    weight: "500 gms",
  },
  {
    id: "ck7",
    name: "Pista Cake (1/2 Kg)",
    description: "Pistachio flavored cream cake",
    price: 449,
    category: "cakes",
    isVeg: true,
    weight: "500 gms",
  },
  {
    id: "ck8",
    name: "Red Velvet Cake (1/2 Kg)",
    description: "Classic red velvet with cream cheese frosting",
    price: 449,
    category: "cakes",
    isVeg: true,
    weight: "500 gms",
  },
  {
    id: "ck9",
    name: "Pineapple Cake (1 Kg)",
    description: "Fresh cream cake with pineapple topping",
    price: 629,
    category: "cakes",
    isVeg: true,
    weight: "1 kg",
  },
  {
    id: "ck10",
    name: "Butterscotch Cake (1 Kg)",
    description: "Caramel-flavored cake with praline",
    price: 689,
    category: "cakes",
    isVeg: true,
    weight: "1 kg",
  },
  {
    id: "ck11",
    name: "Black Forest Cake (1 Kg)",
    description: "Chocolate cake with whipped cream and cherries",
    price: 689,
    category: "cakes",
    isVeg: true,
    weight: "1 kg",
  },
  {
    id: "ck12",
    name: "Chocolate Cake (1 Kg)",
    description: "Rich chocolate cream cake",
    price: 889,
    category: "cakes",
    isVeg: true,
    weight: "1 kg",
  },
  {
    id: "ck13",
    name: "Rasmalai Cake (1 Kg)",
    description: "Fusion cake with rasmalai flavor",
    price: 889,
    category: "cakes",
    isVeg: true,
    weight: "1 kg",
  },
  {
    id: "ck14",
    name: "Almond Cake (1 Kg)",
    description: "Cake with almond crunch and flavor",
    price: 889,
    category: "cakes",
    isVeg: true,
    weight: "1 kg",
  },
  {
    id: "ck15",
    name: "Pista Cake (1 Kg)",
    description: "Pistachio flavored cream cake",
    price: 889,
    category: "cakes",
    isVeg: true,
    weight: "1 kg",
  },
  {
    id: "ck16",
    name: "Red Velvet Cake (1 Kg)",
    description: "Classic red velvet with cream cheese frosting",
    price: 889,
    category: "cakes",
    isVeg: true,
    weight: "1 kg",
  },

  // Snacks (Puffs & Samosas)
  {
    id: "sn1",
    name: "Egg Puff",
    description: "Hard-boiled egg wrapped in flaky pastry",
    price: 25,
    category: "puffs",
    isVeg: false,
  },
  {
    id: "sn2",
    name: "Veg Puff",
    description: "Flaky pastry with seasoned mixed vegetables",
    price: 25,
    category: "puffs",
    isVeg: true,
  },
  {
    id: "sn3",
    name: "Chicken Puff",
    description: "Spiced chicken filling in buttery pastry",
    price: 30,
    category: "puffs",
    isVeg: false,
  },
  {
    id: "sn4",
    name: "Paneer Puff",
    description: "Puff pastry with spiced paneer filling",
    price: 30,
    category: "puffs",
    isVeg: true,
  },
  {
    id: "sn5",
    name: "Samosa",
    description: "Crispy pastry filled with spiced potatoes and peas",
    price: 22,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "sn6",
    name: "Dry Small Samosa",
    description: "Mini crispy samosas, perfect for snacking",
    price: 10,
    category: "snacks",
    isVeg: true,
  },

  // Burgers
  {
    id: "bg1",
    name: "Chicken Burger",
    description: "Crispy chicken patty with fresh veggies",
    price: 90,
    category: "burgers",
    isVeg: false,
  },
  {
    id: "bg2",
    name: "Chicken Cheese Burger",
    description: "Chicken burger with cheese slice",
    price: 100,
    category: "burgers",
    isVeg: false,
  },
  {
    id: "bg3",
    name: "Paneer Burger",
    description: "Grilled paneer patty with mint mayo",
    price: 100,
    category: "burgers",
    isVeg: true,
  },
  {
    id: "bg4",
    name: "Paneer Cheese Burger",
    description: "Paneer burger with melted cheese",
    price: 120,
    category: "burgers",
    isVeg: true,
  },
  {
    id: "bg5",
    name: "Veg Burger",
    description: "Crispy vegetable patty with fresh lettuce",
    price: 80,
    category: "burgers",
    isVeg: true,
  },
  {
    id: "bg6",
    name: "Veg Cheese Burger",
    description: "Veggie burger with cheese topping",
    price: 90,
    category: "burgers",
    isVeg: true,
  },

  // Hot Dogs
  {
    id: "hd1",
    name: "Veg Hot Dog",
    description: "Vegetable sausage in soft bun",
    price: 70,
    category: "hotdogs",
    isVeg: true,
  },
  {
    id: "hd2",
    name: "Veg Cheese Hot Dog",
    description: "Veg hot dog with cheese",
    price: 80,
    category: "hotdogs",
    isVeg: true,
  },
  {
    id: "hd3",
    name: "Paneer Hot Dog",
    description: "Paneer filling in soft bun",
    price: 90,
    category: "hotdogs",
    isVeg: true,
  },
  {
    id: "hd4",
    name: "Paneer Cheese Hot Dog",
    description: "Paneer hot dog with cheese",
    price: 100,
    category: "hotdogs",
    isVeg: true,
  },
  {
    id: "hd5",
    name: "Chicken Hot Dog",
    description: "Chicken sausage in soft bun",
    price: 80,
    category: "hotdogs",
    isVeg: false,
  },
  {
    id: "hd6",
    name: "Chicken Cheese Hot Dog",
    description: "Chicken hot dog with cheese",
    price: 90,
    category: "hotdogs",
    isVeg: false,
  },

  // Sandwiches
  {
    id: "sd1",
    name: "Veg Cheese Grill Sandwich",
    description: "Grilled sandwich with veggies and cheese",
    price: 60,
    category: "sandwiches",
    isVeg: true,
  },
  {
    id: "sd2",
    name: "Chicken Cheese Grill Sandwich",
    description: "Grilled chicken sandwich with cheese",
    price: 80,
    category: "sandwiches",
    isVeg: false,
  },
  {
    id: "sd3",
    name: "Veg Roasted Sandwich",
    description: "Roasted vegetable sandwich",
    price: 40,
    category: "sandwiches",
    isVeg: true,
  },
  {
    id: "sd4",
    name: "Chicken Roasted Sandwich",
    description: "Roasted chicken sandwich",
    price: 60,
    category: "sandwiches",
    isVeg: false,
  },

  // Pizzas
  {
    id: "pz1",
    name: "Veg Cheese Pizza",
    description: "Pizza loaded with fresh vegetables and cheese",
    price: 219,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz2",
    name: "Plain Cheese Pizza",
    description: "Classic cheese pizza with tomato sauce",
    price: 219,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz3",
    name: "Sweet Corn Cheese Pizza",
    description: "Sweet corn and cheese pizza",
    price: 229,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz4",
    name: "Tomato Cheese Pizza",
    description: "Fresh tomato and cheese pizza",
    price: 219,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz5",
    name: "Capsicum Cheese Pizza",
    description: "Bell pepper and cheese pizza",
    price: 219,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz6",
    name: "Paneer Cheese Pizza",
    description: "Paneer cubes with cheese and spices",
    price: 249,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz7",
    name: "Chicken Cheese Pizza",
    description: "Chicken pieces with cheese and sauce",
    price: 249,
    category: "pizza",
    isVeg: false,
  },

  // Pastries
  {
    id: "ps1",
    name: "Pineapple Pastry",
    description: "Light sponge with pineapple chunks and cream",
    price: 55,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps2",
    name: "Butterscotch Pastry",
    description: "Caramel-flavored pastry with praline crunch",
    price: 65,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps3",
    name: "Black Forest Pastry",
    description: "Classic chocolate layers with cherries and cream",
    price: 75,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps4",
    name: "Chocolate Pastry",
    description: "Rich chocolate cream pastry",
    price: 90,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps5",
    name: "Rasmalai Pastry",
    description: "Fusion pastry with rasmalai flavor",
    price: 90,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps6",
    name: "Almond Pastry",
    description: "Pastry with almond crunch",
    price: 90,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps7",
    name: "Pista Pastry",
    description: "Pistachio flavored pastry",
    price: 90,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps8",
    name: "Red Velvet Pastry",
    description: "Velvety sponge with cream cheese frosting",
    price: 90,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps9",
    name: "Choco Lava",
    description: "Warm chocolate cake with molten center",
    price: 80,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps10",
    name: "Chocolate Donuts",
    description: "Ring shaped chocolate pastry",
    price: 70,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps11",
    name: "Chocolate Brownie",
    description: "Dense fudgy chocolate brownie",
    price: 100,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps12",
    name: "Cup Cake",
    description: "Individual sized vanilla/chocolate cupcake",
    price: 40,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps13",
    name: "Mini Cup Cake",
    description: "Bite-sized cupcake",
    price: 30,
    category: "pastries",
    isVeg: true,
  },

  // Biscuits - 250 Gms packs
  {
    id: "bc1",
    name: "Salt Biscuits",
    description: "Savory tea-time crackers",
    price: 80,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc2",
    name: "Osmania Biscuits",
    description: "Hyderabad's iconic sweet-salty tea biscuits",
    price: 80,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc3",
    name: "Chand Biscuits",
    description: "Crescent-shaped cookies with cardamom",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc4",
    name: "Vanilla Kaju Biscuits",
    description: "Vanilla flavored cashew cookies",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc5",
    name: "Chocolate Kaju Biscuits",
    description: "Chocolate cashew cookies",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc6",
    name: "Choco Chips Biscuits",
    description: "Cookies with chocolate chips",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc7",
    name: "Badam Biscuits",
    description: "Almond flavored cookies",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc8",
    name: "Fruit Biscuits",
    description: "Sweet cookies with tutti-frutti",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc9",
    name: "Almond Biscuits",
    description: "Premium cookies with roasted almonds",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc10",
    name: "Cake Rusk Biscuits",
    description: "Crispy twice-baked cake slices",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc11",
    name: "Chocolate Cake Rusk Biscuits",
    description: "Chocolate flavored crispy rusks",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
];

export const SHOP_INFO = {
  name: "Amogha Pure Ghee Sweets & Bakers",
  tagline: "Fresh • Delicious • Hyderabadi Special",
  address: "Jodimetla, Pocharam, Hyderabad",
  plusCode: "CJFW+X4X Hyderabad",
  googleMapsUrl: "https://www.google.com/maps/place/CJFW%2BX4X,+Jodimetla,+Pocharam,+Hyderabad,+Telangana",
  whatsappNumber: "+918886002890",
  phoneNumber: "+918886002890",
  hours: "7:00 AM - 10:00 PM",
  email: "amoghasweets@gmail.com",
} as const;
