export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  isVeg?: boolean;
  weight?: string;
  perfectMatch?: string;
  image?: string;
}

export const categories = [
  { id: "pizza", name: "Pizza", icon: "🍕" },
  { id: "burgers", name: "Burgers", icon: "🍔" },
  { id: "snacks", name: "Chat & Snacks", icon: "🍢" },
  { id: "puffs", name: "Puffs", icon: "🥐" },
  { id: "biscuits", name: "Biscuits", icon: "🍪" },
  { id: "pastries", name: "Pastries", icon: "🍰" },
  { id: "cakes", name: "Cakes", icon: "🎂" },
] as const;

export const menuItems: MenuItem[] = [
  // Pizza
  {
    id: "p1",
    name: "Margherita Pizza",
    description: "Classic tomato sauce with mozzarella cheese and fresh basil",
    price: 149,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "p2",
    name: "Veggie Supreme Pizza",
    description: "Loaded with bell peppers, onions, tomatoes, corn, and olives",
    price: 199,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "p3",
    name: "Paneer Tikka Pizza",
    description: "Tandoori paneer cubes with spicy sauce and herbs",
    price: 229,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "p4",
    name: "Chicken Pizza",
    description: "Grilled chicken with signature sauce and cheese",
    price: 249,
    category: "pizza",
    isVeg: false,
  },

  // Burgers
  {
    id: "b1",
    name: "Veggie Burger",
    description: "Crispy vegetable patty with fresh lettuce and special sauce",
    price: 79,
    category: "burgers",
    isVeg: true,
  },
  {
    id: "b2",
    name: "Cheese Burger",
    description: "Double cheese slice with caramelized onions",
    price: 99,
    category: "burgers",
    isVeg: true,
  },
  {
    id: "b3",
    name: "Paneer Burger",
    description: "Grilled paneer patty with mint mayo",
    price: 119,
    category: "burgers",
    isVeg: true,
  },
  {
    id: "b4",
    name: "Chicken Burger",
    description: "Crispy fried chicken with coleslaw",
    price: 139,
    category: "burgers",
    isVeg: false,
  },

  // Chat & Snacks
  {
    id: "s1",
    name: "Samosa",
    description: "Crispy pastry filled with spiced potatoes and peas",
    price: 20,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "s2",
    name: "Kachori",
    description: "Flaky pastry with spicy lentil filling",
    price: 25,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "s3",
    name: "Vada Pav",
    description: "Mumbai's favorite potato fritter in a bun",
    price: 35,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "s4",
    name: "Bhel Puri",
    description: "Crispy puffed rice with chutneys and sev",
    price: 45,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "s5",
    name: "Sev Puri",
    description: "Flat puris topped with potato, onion, and chutneys",
    price: 50,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "s6",
    name: "Dahi Puri",
    description: "Hollow puris filled with yogurt and chutneys",
    price: 55,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "s7",
    name: "Pani Puri",
    description: "Crispy shells filled with spicy flavored water",
    price: 40,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "s8",
    name: "Spring Rolls",
    description: "Crispy vegetable-filled rolls with sweet chili sauce",
    price: 69,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "s9",
    name: "Bread Pakora",
    description: "Bread slices dipped in spiced batter and fried",
    price: 35,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "s10",
    name: "Cutlet",
    description: "Mixed vegetable cutlet with mint chutney",
    price: 45,
    category: "snacks",
    isVeg: true,
  },

  // Puffs
  {
    id: "pf1",
    name: "Veg Puff",
    description: "Flaky pastry with seasoned mixed vegetables",
    price: 25,
    category: "puffs",
    isVeg: true,
  },
  {
    id: "pf2",
    name: "Paneer Puff",
    description: "Puff pastry with spiced paneer filling",
    price: 35,
    category: "puffs",
    isVeg: true,
  },
  {
    id: "pf3",
    name: "Egg Puff",
    description: "Hard-boiled egg wrapped in flaky pastry",
    price: 30,
    category: "puffs",
    isVeg: false,
  },
  {
    id: "pf4",
    name: "Chicken Puff",
    description: "Spiced chicken filling in buttery pastry",
    price: 45,
    category: "puffs",
    isVeg: false,
  },
  {
    id: "pf5",
    name: "Aloo Puff",
    description: "Classic potato masala in crispy layers",
    price: 20,
    category: "puffs",
    isVeg: true,
  },

  // Biscuits - Hyderabadi Special
  {
    id: "bc1",
    name: "Osmania Biscuits",
    description: "Hyderabad's iconic sweet-salty tea biscuits",
    price: 60,
    category: "biscuits",
    isVeg: true,
    weight: "250 G",
    perfectMatch: "Pairs best with Irani Chai ☕",
  },
  {
    id: "bc2",
    name: "Chand Biscuits",
    description: "Crescent-shaped cookies with cardamom flavor",
    price: 65,
    category: "biscuits",
    isVeg: true,
    weight: "250 G",
    perfectMatch: "A local favorite with hot milk! 🥛",
  },
  {
    id: "bc3",
    name: "Salt Biscuits",
    description: "Savory tea-time crackers, light and crispy",
    price: 50,
    category: "biscuits",
    isVeg: true,
    weight: "250 G",
    perfectMatch: "Perfect with evening chai ☕",
  },
  {
    id: "bc4",
    name: "Fruit Biscuits",
    description: "Sweet cookies with tutti-frutti pieces",
    price: 70,
    category: "biscuits",
    isVeg: true,
    weight: "250 G",
    perfectMatch: "Kids love these with milk 🍼",
  },
  {
    id: "bc5",
    name: "Cashew Biscuits",
    description: "Rich buttery cookies topped with cashews",
    price: 85,
    category: "biscuits",
    isVeg: true,
    weight: "250 G",
    perfectMatch: "A festive treat for guests 🎉",
  },
  {
    id: "bc6",
    name: "Almond Biscuits",
    description: "Premium cookies with roasted almonds",
    price: 90,
    category: "biscuits",
    isVeg: true,
    weight: "250 G",
    perfectMatch: "Perfect for gifting! 🎁",
  },

  // Pastries
  {
    id: "ps1",
    name: "Rasmalai Pastry",
    description: "Fusion pastry with rasmalai flavor and saffron cream",
    price: 85,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps2",
    name: "Choco Lava Cake",
    description: "Warm chocolate cake with molten center",
    price: 95,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps3",
    name: "Black Forest Pastry",
    description: "Classic chocolate layers with cherries and cream",
    price: 90,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps4",
    name: "Pineapple Pastry",
    description: "Light sponge with pineapple chunks and cream",
    price: 75,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps5",
    name: "Butterscotch Pastry",
    description: "Caramel-flavored pastry with praline crunch",
    price: 80,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps6",
    name: "Strawberry Pastry",
    description: "Fresh strawberry cream on vanilla sponge",
    price: 85,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps7",
    name: "Mango Pastry",
    description: "Seasonal mango delight with fresh pulp",
    price: 95,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps8",
    name: "Red Velvet Pastry",
    description: "Velvety red sponge with cream cheese frosting",
    price: 100,
    category: "pastries",
    isVeg: true,
  },

  // Cakes
  {
    id: "ck1",
    name: "Black Forest Cake",
    description: "1/2 kg chocolate cake with whipped cream and cherries",
    price: 350,
    category: "cakes",
    isVeg: true,
  },
  {
    id: "ck2",
    name: "Pineapple Cake",
    description: "1/2 kg fresh cream cake with pineapple topping",
    price: 320,
    category: "cakes",
    isVeg: true,
  },
  {
    id: "ck3",
    name: "Butterscotch Cake",
    description: "1/2 kg caramel-flavored celebration cake",
    price: 340,
    category: "cakes",
    isVeg: true,
  },
  {
    id: "ck4",
    name: "Chocolate Truffle Cake",
    description: "1/2 kg rich dark chocolate ganache cake",
    price: 400,
    category: "cakes",
    isVeg: true,
  },
  {
    id: "ck5",
    name: "Strawberry Cake",
    description: "1/2 kg fresh strawberry cream cake",
    price: 360,
    category: "cakes",
    isVeg: true,
  },
  {
    id: "ck6",
    name: "Red Velvet Cake",
    description: "1/2 kg classic red velvet with cream cheese",
    price: 380,
    category: "cakes",
    isVeg: true,
  },
  {
    id: "ck7",
    name: "Mango Cake",
    description: "1/2 kg seasonal mango special cake",
    price: 370,
    category: "cakes",
    isVeg: true,
  },
  {
    id: "ck8",
    name: "Fruit Cake",
    description: "1/2 kg mixed fresh fruit cream cake",
    price: 390,
    category: "cakes",
    isVeg: true,
  },
];

export const SHOP_INFO = {
  name: "Amogha Sweets and Bakers",
  tagline: "Fresh • Delicious • Hyderabadi Special",
  address: "Jodimetla, Pocharam, Hyderabad",
  plusCode: "CJFW+X4X Hyderabad",
  googleMapsUrl: "https://www.google.com/maps/place/CJFW%2BX4X,+Jodimetla,+Pocharam,+Hyderabad,+Telangana",
  whatsappNumber: "+918886002890",
  phoneNumber: "+918886002890",
  hours: "7:00 AM - 10:00 PM",
  email: "amoghasweets@gmail.com",
} as const;
