export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  isVeg?: boolean;
  weight?: string;
  perfectMatch?: string;
  image?: string;
  price250g?: number;
  price500g?: number;
  price1kg?: number;
}

export const categories = [
  { id: "sweets", name: "Sweets", icon: "🍬" },
  { id: "namkeens", name: "Namkeens", icon: "🧂" },
  { id: "chat", name: "Chat", icon: "🍽️" },
  { id: "cakes", name: "Cakes", icon: "🎂" },
  { id: "snacks", name: "Snacks", icon: "🍢" },
  { id: "burgers", name: "Burgers", icon: "🍔" },
  { id: "hotdogs", name: "Hot Dogs", icon: "🌭" },
  { id: "sandwiches", name: "Sandwiches", icon: "🥪" },
  { id: "pizza", name: "Pizzas", icon: "🍕" },
  { id: "pastries", name: "Pastries", icon: "🍰" },
  { id: "biscuits", name: "Biscuits", icon: "🍪" },
] as const;

export const menuItems: MenuItem[] = [
  // Sweets - Mixed Sweets
  {
    id: "sw1",
    name: "Mixed Sweets",
    description: "Assorted variety of traditional Indian sweets",
    price: 195,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 195,
    price500g: 390,
    price1kg: 780,
  },
  {
    id: "sw2",
    name: "Motichur Laddu",
    description: "Golden besan pearls soaked in sugar syrup",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw3",
    name: "Ajmeri Kalakand",
    description: "Rich milk cake with soft grainy texture",
    price: 195,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 195,
    price500g: 390,
    price1kg: 780,
  },
  {
    id: "sw4",
    name: "White Kalakand",
    description: "Creamy white milk fudge delicacy",
    price: 195,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 195,
    price500g: 390,
    price1kg: 780,
  },
  {
    id: "sw5",
    name: "Badusha",
    description: "Flaky layered sweet soaked in sugar syrup",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw6",
    name: "Kova Puri",
    description: "Traditional sweet with rich kova filling",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw7",
    name: "Madatha Khaja",
    description: "Layered crispy sweet pastry",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw8",
    name: "Dry Fruit Halwa",
    description: "Rich halwa loaded with premium dry fruits",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 380,
    price1kg: 760,
  },
  {
    id: "sw9",
    name: "Bombay Halwa",
    description: "Colorful translucent jelly-like sweet",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 380,
    price1kg: 760,
  },
  {
    id: "sw10",
    name: "Bandar Laddu",
    description: "Famous laddu from Bandar with unique texture",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw11",
    name: "Beshan Laddu",
    description: "Traditional gram flour laddu",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw12",
    name: "Boondi Laddu",
    description: "Sweet laddus made from boondi pearls",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw13",
    name: "Nuvvula Laddu (Til Laddu)",
    description: "Sesame seeds laddu with jaggery",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw14",
    name: "Ice Cream Burfi",
    description: "Creamy burfi with ice cream flavor",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw15",
    name: "Vanilla Burfi",
    description: "Soft vanilla flavored milk burfi",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw16",
    name: "Standard Burfi",
    description: "Classic milk burfi with rich texture",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw17",
    name: "Soan Patti",
    description: "Crispy flaky sweet with delicate layers",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw18",
    name: "Soan Papidi",
    description: "Traditional flaky sweet cube",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw19",
    name: "Milk Mysore Pack",
    description: "Rich milk-based mysore pak",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw20",
    name: "Jali Mysore Pack",
    description: "Crispy netted mysore pak variant",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw21",
    name: "Bellam Sunnundalu",
    description: "Urad dal laddu with jaggery",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw22",
    name: "Sugar Sunnundalu",
    description: "Urad dal laddu with sugar",
    price: 185,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 185,
    price500g: 370,
    price1kg: 740,
  },
  {
    id: "sw23",
    name: "Dry Fruit Bellam Putharekulu (3 Pieces)",
    description: "Crispy jaggery rolls with dry fruits - 3 pieces",
    price: 150,
    category: "sweets",
    isVeg: true,
  },
  {
    id: "sw24",
    name: "Bellam Putharekulu (3 Pieces)",
    description: "Traditional jaggery filled crispy rolls - 3 pieces",
    price: 120,
    category: "sweets",
    isVeg: true,
  },
  {
    id: "sw25",
    name: "Sugar Putharekulu (3 Pieces)",
    description: "Crispy sugar filled traditional rolls - 3 pieces",
    price: 100,
    category: "sweets",
    isVeg: true,
  },
  {
    id: "sw26",
    name: "Rasmalai (3 Pieces)",
    description: "Soft cheese patties in saffron milk - 3 pieces",
    price: 120,
    category: "sweets",
    isVeg: true,
  },
  {
    id: "sw27",
    name: "Rasagulla (3 Pieces)",
    description: "Spongy syrup soaked cheese balls - 3 pieces",
    price: 120,
    category: "sweets",
    isVeg: true,
  },
  {
    id: "sw28",
    name: "Gulab Jamun (3 Pieces)",
    description: "Deep fried milk solids in sugar syrup - 3 pieces",
    price: 120,
    category: "sweets",
    isVeg: true,
  },
  {
    id: "sw29",
    name: "Kala Jamun (3 Pieces)",
    description: "Dark fried jamuns with caramelized crust - 3 pieces",
    price: 120,
    category: "sweets",
    isVeg: true,
  },
  // Dry Fruit Sweets
  {
    id: "sw30",
    name: "Kaju Barfi",
    description: "Premium cashew nut fudge",
    price: 350,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 350,
    price500g: 700,
    price1kg: 1400,
  },
  {
    id: "sw31",
    name: "Kaju Kathli",
    description: "Diamond shaped cashew sweet",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },
  {
    id: "sw32",
    name: "All Dry Fruit Mixed Sweets",
    description: "Assorted premium dry fruit sweets",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },
  {
    id: "sw33",
    name: "Anjeer Roll",
    description: "Premium fig rolls with nuts",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },
  {
    id: "sw34",
    name: "Kaju Pista Roll",
    description: "Rich roll of cashew and pistachio",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },
  {
    id: "sw35",
    name: "Kaju Chikki",
    description: "Cashew nut brittle",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },
  {
    id: "sw36",
    name: "Dry Fruit Laddu",
    description: "Nutritious laddu with mixed dry fruits",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },
  {
    id: "sw37",
    name: "Dry Fruit Chikki",
    description: "Mixed dry fruit brittle",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },
  {
    id: "sw38",
    name: "Kaju Bites",
    description: "Bite-sized cashew treats",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },
  {
    id: "sw39",
    name: "Kaju Sandwich",
    description: "Layered cashew sweet sandwich",
    price: 390,
    category: "sweets",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },

  // Namkeens
  {
    id: "nk1",
    name: "Amogha Special Mixture",
    description: "Signature spicy mixture with premium ingredients",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 120,
    price500g: 240,
    price1kg: 480,
  },
  {
    id: "nk2",
    name: "Special Khara Boondi",
    description: "Spicy gram flour pearls",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 120,
    price500g: 240,
    price1kg: 480,
  },
  {
    id: "nk3",
    name: "Kaju Mixture",
    description: "Premium mixture with cashew nuts",
    price: 150,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 150,
    price500g: 300,
    price1kg: 600,
  },
  {
    id: "nk4",
    name: "Batana Mixture",
    description: "Chickpea based spicy mixture",
    price: 150,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 150,
    price500g: 300,
    price1kg: 600,
  },
  {
    id: "nk5",
    name: "Dalmoti",
    description: "Spiced lentils snack",
    price: 150,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 150,
    price500g: 300,
    price1kg: 600,
  },
  {
    id: "nk6",
    name: "Masala Palli",
    description: "Spiced groundnut snack",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 120,
    price500g: 240,
    price1kg: 480,
  },
  {
    id: "nk7",
    name: "Khara Pusa",
    description: "Spicy puffed rice snack",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 120,
    price500g: 240,
    price1kg: 480,
  },
  {
    id: "nk8",
    name: "Masala Mixture",
    description: "Classic spicy mixture",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 120,
    price500g: 240,
    price1kg: 480,
  },
  {
    id: "nk9",
    name: "Corn Mixture",
    description: "Crispy corn flakes mixture",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 120,
    price500g: 240,
    price1kg: 480,
  },
  {
    id: "nk10",
    name: "Ghatiya",
    description: "Traditional sev snack",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 120,
    price500g: 240,
    price1kg: 480,
  },
  {
    id: "nk11",
    name: "Papdi",
    description: "Crispy savory discs",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 120,
    price500g: 240,
    price1kg: 480,
  },
  {
    id: "nk12",
    name: "Namak Pare",
    description: "Salty fried flour crisps",
    price: 120,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 120,
    price500g: 240,
    price1kg: 480,
  },
  {
    id: "nk13",
    name: "Ghee Roasted Salted Kaju",
    description: "Premium ghee roasted salted cashews",
    price: 390,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },
  {
    id: "nk14",
    name: "Ghee Roasted Masala Kaju",
    description: "Spiced ghee roasted cashews",
    price: 390,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },
  {
    id: "nk15",
    name: "Ghee Roasted Pepper Kaju",
    description: "Pepper flavored ghee roasted cashews",
    price: 390,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },
  {
    id: "nk16",
    name: "Ghee Roasted Almonds",
    description: "Premium ghee roasted almonds",
    price: 390,
    category: "namkeens",
    isVeg: true,
    weight: "250 gms",
    price250g: 390,
    price500g: 780,
    price1kg: 1560,
  },

  // Cakes - 1/2 Kg
  {
    id: "ck1",
    name: "Pineapple Cake (1/2 Kg)",
    description: "Fresh cream cake with pineapple topping - 1/2 Kg",
    price: 319,
    category: "cakes",
    isVeg: true,
    weight: "1/2 Kg",
  },
  {
    id: "ck2",
    name: "Butterscotch Cake (1/2 Kg)",
    description: "Caramel-flavored celebration cake - 1/2 Kg",
    price: 349,
    category: "cakes",
    isVeg: true,
    weight: "1/2 Kg",
  },
  {
    id: "ck3",
    name: "Black Forest Cake (1/2 Kg)",
    description: "Chocolate cake with whipped cream and cherries - 1/2 Kg",
    price: 349,
    category: "cakes",
    isVeg: true,
    weight: "1/2 Kg",
  },
  {
    id: "ck4",
    name: "Chocolate Cake (1/2 Kg)",
    description: "Rich dark chocolate cake - 1/2 Kg",
    price: 449,
    category: "cakes",
    isVeg: true,
    weight: "1/2 Kg",
  },
  {
    id: "ck5",
    name: "Rasmalai Cake (1/2 Kg)",
    description: "Fusion cake with rasmalai flavor - 1/2 Kg",
    price: 449,
    category: "cakes",
    isVeg: true,
    weight: "1/2 Kg",
  },
  {
    id: "ck6",
    name: "Almond Cake (1/2 Kg)",
    description: "Cake loaded with almond goodness - 1/2 Kg",
    price: 449,
    category: "cakes",
    isVeg: true,
    weight: "1/2 Kg",
  },
  {
    id: "ck7",
    name: "Pista Cake (1/2 Kg)",
    description: "Pistachio flavored cake - 1/2 Kg",
    price: 449,
    category: "cakes",
    isVeg: true,
    weight: "1/2 Kg",
  },
  {
    id: "ck8",
    name: "Red Velvet Cake (1/2 Kg)",
    description: "Classic red velvet with cream cheese - 1/2 Kg",
    price: 449,
    category: "cakes",
    isVeg: true,
    weight: "1/2 Kg",
  },
  // Cakes - 1 Kg
  {
    id: "ck9",
    name: "Pineapple Cake (1 Kg)",
    description: "Fresh cream cake with pineapple topping - 1 Kg",
    price: 629,
    category: "cakes",
    isVeg: true,
    weight: "1 Kg",
  },
  {
    id: "ck10",
    name: "Butterscotch Cake (1 Kg)",
    description: "Caramel-flavored celebration cake - 1 Kg",
    price: 689,
    category: "cakes",
    isVeg: true,
    weight: "1 Kg",
  },
  {
    id: "ck11",
    name: "Black Forest Cake (1 Kg)",
    description: "Chocolate cake with whipped cream and cherries - 1 Kg",
    price: 689,
    category: "cakes",
    isVeg: true,
    weight: "1 Kg",
  },
  {
    id: "ck12",
    name: "Chocolate Cake (1 Kg)",
    description: "Rich dark chocolate cake - 1 Kg",
    price: 889,
    category: "cakes",
    isVeg: true,
    weight: "1 Kg",
  },
  {
    id: "ck13",
    name: "Rasmalai Cake (1 Kg)",
    description: "Fusion cake with rasmalai flavor - 1 Kg",
    price: 889,
    category: "cakes",
    isVeg: true,
    weight: "1 Kg",
  },
  {
    id: "ck14",
    name: "Almond Cake (1 Kg)",
    description: "Cake loaded with almond goodness - 1 Kg",
    price: 889,
    category: "cakes",
    isVeg: true,
    weight: "1 Kg",
  },
  {
    id: "ck15",
    name: "Pista Cake (1 Kg)",
    description: "Pistachio flavored cake - 1 Kg",
    price: 889,
    category: "cakes",
    isVeg: true,
    weight: "1 Kg",
  },
  {
    id: "ck16",
    name: "Red Velvet Cake (1 Kg)",
    description: "Classic red velvet with cream cheese - 1 Kg",
    price: 889,
    category: "cakes",
    isVeg: true,
    weight: "1 Kg",
  },

  // Snacks (Puffs & More)
  {
    id: "sn1",
    name: "Egg Puff",
    description: "Flaky pastry with hard-boiled egg filling",
    price: 25,
    category: "snacks",
    isVeg: false,
  },
  {
    id: "sn2",
    name: "Veg Puff",
    description: "Flaky pastry with seasoned mixed vegetables",
    price: 25,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "sn3",
    name: "Chicken Puff",
    description: "Flaky pastry with spiced chicken filling",
    price: 30,
    category: "snacks",
    isVeg: false,
  },
  {
    id: "sn4",
    name: "Paneer Puff",
    description: "Flaky pastry with spiced paneer filling",
    price: 30,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "sn5",
    name: "Samosa",
    description: "Crispy pastry filled with spiced potatoes",
    price: 22,
    category: "snacks",
    isVeg: true,
  },
  {
    id: "sn6",
    name: "Dry Small Samosa",
    description: "Mini crispy samosas",
    price: 10,
    category: "snacks",
    isVeg: true,
  },

  // Burgers
  {
    id: "bg1",
    name: "Chicken Burger",
    description: "Crispy chicken patty with fresh veggies",
    price: 90,
    category: "burgers",
    isVeg: false,
  },
  {
    id: "bg2",
    name: "Chicken Cheese Burger",
    description: "Chicken burger with melted cheese",
    price: 100,
    category: "burgers",
    isVeg: false,
  },
  {
    id: "bg3",
    name: "Paneer Burger",
    description: "Grilled paneer patty with fresh veggies",
    price: 100,
    category: "burgers",
    isVeg: true,
  },
  {
    id: "bg4",
    name: "Paneer Cheese Burger",
    description: "Paneer burger with melted cheese",
    price: 120,
    category: "burgers",
    isVeg: true,
  },
  {
    id: "bg5",
    name: "Veg Burger",
    description: "Crispy vegetable patty with fresh veggies",
    price: 80,
    category: "burgers",
    isVeg: true,
  },
  {
    id: "bg6",
    name: "Veg Cheese Burger",
    description: "Veg burger with melted cheese",
    price: 90,
    category: "burgers",
    isVeg: true,
  },

  // Hot Dogs
  {
    id: "hd1",
    name: "Veg Hot Dog",
    description: "Vegetable sausage in soft bun",
    price: 70,
    category: "hotdogs",
    isVeg: true,
  },
  {
    id: "hd2",
    name: "Veg Cheese Hot Dog",
    description: "Veg hot dog with melted cheese",
    price: 80,
    category: "hotdogs",
    isVeg: true,
  },
  {
    id: "hd3",
    name: "Paneer Hot Dog",
    description: "Paneer sausage in soft bun",
    price: 90,
    category: "hotdogs",
    isVeg: true,
  },
  {
    id: "hd4",
    name: "Paneer Cheese Hot Dog",
    description: "Paneer hot dog with melted cheese",
    price: 100,
    category: "hotdogs",
    isVeg: true,
  },
  {
    id: "hd5",
    name: "Chicken Hot Dog",
    description: "Chicken sausage in soft bun",
    price: 80,
    category: "hotdogs",
    isVeg: false,
  },
  {
    id: "hd6",
    name: "Chicken Cheese Hot Dog",
    description: "Chicken hot dog with melted cheese",
    price: 90,
    category: "hotdogs",
    isVeg: false,
  },

  // Sandwiches
  {
    id: "swch1",
    name: "Veg Cheese Grill Sandwich",
    description: "Grilled sandwich with veggies and cheese",
    price: 60,
    category: "sandwiches",
    isVeg: true,
  },
  {
    id: "swch2",
    name: "Chicken Cheese Grill Sandwich",
    description: "Grilled sandwich with chicken and cheese",
    price: 80,
    category: "sandwiches",
    isVeg: false,
  },
  {
    id: "swch3",
    name: "Veg Roasted Sandwich",
    description: "Roasted vegetable sandwich",
    price: 40,
    category: "sandwiches",
    isVeg: true,
  },
  {
    id: "swch4",
    name: "Chicken Roasted Sandwich",
    description: "Roasted chicken sandwich",
    price: 60,
    category: "sandwiches",
    isVeg: false,
  },

  // Pizzas
  {
    id: "pz1",
    name: "Veg Cheese Pizza",
    description: "Classic pizza with mixed vegetables",
    price: 219,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz2",
    name: "Plain Cheese Pizza",
    description: "Simple cheese pizza with tomato sauce",
    price: 219,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz3",
    name: "Sweet Corn Cheese Pizza",
    description: "Pizza loaded with sweet corn",
    price: 229,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz4",
    name: "Tomato Cheese Pizza",
    description: "Fresh tomato and cheese pizza",
    price: 219,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz5",
    name: "Capsicum Cheese Pizza",
    description: "Bell pepper and cheese pizza",
    price: 219,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz6",
    name: "Paneer Cheese Pizza",
    description: "Pizza with paneer cubes",
    price: 249,
    category: "pizza",
    isVeg: true,
  },
  {
    id: "pz7",
    name: "Chicken Cheese Pizza",
    description: "Pizza with chicken pieces",
    price: 249,
    category: "pizza",
    isVeg: false,
  },

  // Pastries
  {
    id: "ps1",
    name: "Pineapple Pastry",
    description: "Light sponge with pineapple and cream",
    price: 55,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps2",
    name: "Butterscotch Pastry",
    description: "Caramel-flavored pastry with crunch",
    price: 65,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps3",
    name: "Black Forest Pastry",
    description: "Chocolate layers with cherries and cream",
    price: 75,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps4",
    name: "Chocolate Pastry",
    description: "Rich chocolate pastry",
    price: 90,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps5",
    name: "Rasmalai Pastry",
    description: "Fusion pastry with rasmalai flavor",
    price: 90,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps6",
    name: "Almond Pastry",
    description: "Pastry loaded with almonds",
    price: 90,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps7",
    name: "Pista Pastry",
    description: "Pistachio flavored pastry",
    price: 90,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps8",
    name: "Red Velvet Pastry",
    description: "Velvety sponge with cream cheese frosting",
    price: 90,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps9",
    name: "Choco Lava",
    description: "Warm chocolate cake with molten center",
    price: 80,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps10",
    name: "Chocolate Donuts",
    description: "Chocolate glazed donuts",
    price: 70,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps11",
    name: "Chocolate Brownie",
    description: "Rich chocolate brownie",
    price: 100,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps12",
    name: "Cup Cake",
    description: "Regular size cupcake",
    price: 40,
    category: "pastries",
    isVeg: true,
  },
  {
    id: "ps13",
    name: "Mini Cup Cake",
    description: "Bite-sized cupcakes",
    price: 30,
    category: "pastries",
    isVeg: true,
  },

  // Biscuits
  {
    id: "bc1",
    name: "Salt Biscuits (250 Gms)",
    description: "Savory tea-time crackers, light and crispy - 250 Gms",
    price: 80,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc2",
    name: "Osmania Biscuits (250 Gms)",
    description: "Hyderabad's iconic sweet-salty tea biscuits - 250 Gms",
    price: 80,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
    perfectMatch: "Pairs best with Irani Chai",
  },
  {
    id: "bc3",
    name: "Chand Biscuits (250 Gms)",
    description: "Crescent-shaped cookies with cardamom flavor - 250 Gms",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc4",
    name: "Vanilla Kaju Biscuits (250 Gms)",
    description: "Vanilla flavored cashew biscuits - 250 Gms",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc5",
    name: "Chocolate Kaju Biscuits (250 Gms)",
    description: "Chocolate cashew biscuits - 250 Gms",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc6",
    name: "Choco Chips Biscuits (250 Gms)",
    description: "Biscuits with chocolate chips - 250 Gms",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc7",
    name: "Badam Biscuits (250 Gms)",
    description: "Almond flavored biscuits - 250 Gms",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc8",
    name: "Fruit Biscuits (250 Gms)",
    description: "Sweet cookies with tutti-frutti - 250 Gms",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc9",
    name: "Almond Biscuits (250 Gms)",
    description: "Premium cookies with almonds - 250 Gms",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc10",
    name: "Cake Rusk Biscuits (250 Gms)",
    description: "Crispy cake rusks - 250 Gms",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
  {
    id: "bc11",
    name: "Chocolate Cake Rusk Biscuits (250 Gms)",
    description: "Chocolate flavored crispy cake rusks - 250 Gms",
    price: 100,
    category: "biscuits",
    isVeg: true,
    weight: "250 Gms",
  },
];

export const SHOP_INFO = {
  name: "Amogha Sweets and Bakers",
  tagline: "Fresh • Delicious • Hyderabadi Special",
  address: "Jodimetla, Pocharam, Hyderabad",
  plusCode: "CJFW+X4X Hyderabad",
  googleMapsUrl: "https://www.google.com/maps/place/CJFW%2BX4X,+Jodimetla,+Pocharam,+Hyderabad,+Telangana",
  whatsappNumber: "+918886002890",
  phoneNumber: "+918886002890",
  hours: "7:00 AM - 10:00 PM",
  email: "amoghasweets@gmail.com",
} as const;

